pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nodejs-repo-creds', 
                                                 usernameVariable: 'GIT_USERNAME', 
                                                 passwordVariable: 'GIT_PASSWORD')]) {
                git branch: 'main', 
                    credentialsId: 'nodejs-repo-creds',
                    url: 'https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/aftabkhan999/node-js-getting-started.git'
                }
                sh """
                  ls -ltra
                """
            }
        }
        stage('build project') {
            steps {
                sh """
                cd node-js-getting-started
                npm install
                npm start
                """
            }
        }
    }
}
